package com.aranaira.magichem.config;

import com.aranaira.magichem.MagiChemMod;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.config.ModConfigEvent;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.*;

// An example config class. This is not required, but it's a good idea to have one to keep your config organized.
// Demonstrates how to use Forge's config APIs
@Mod.EventBusSubscriber(modid = MagiChemMod.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ServerConfig
{
    private static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();

    //----------------GENERAL

    private static final ForgeConfigSpec.IntValue GRIME_PER_WASTE = BUILDER
            .comment("How much Grime is consumed to make a single unit of Alchemical Waste when cleaning an alchemical device.")
            .defineInRange("grimePerWaste", 1200, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue GRIME_PENALTY_POINT = BUILDER
            .comment("At what percent full of Grime that alchemical devices start to lose Efficiency and gain Operation Time.")
            .defineInRange("grimePenaltyPoint", 50, 1, 100);

    private static final ForgeConfigSpec.IntValue FLUID_PER_XP_POINT = BUILDER
            .comment("How many mB of Academic Slurry constitutes one experience point.")
            .defineInRange("fluidPerXPPoint", 100, 1, 1000);

    private static final ForgeConfigSpec.IntValue CONSTRUCT_STUDY_EXPERIENCE_SIMPLE = BUILDER
            .comment("How many experience points a Studying construct generates from simple study materials.")
            .defineInRange("constructStudyExperienceSimple", 12, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue CONSTRUCT_STUDY_EXPERIENCE_ADVANCED = BUILDER
            .comment("How many experience points a Studying construct generates from advanced study materials.")
            .defineInRange("constructStudyExperienceAdvanced", 40, 2, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue CONSTRUCT_STUDY_EXPERIENCE_MASTER = BUILDER
            .comment("How many experience points a Studying construct generates from master study materials.")
            .defineInRange("constructStudyExperienceMaster", 145, 4, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue HOUSE_OF_ALCHEMY_DISTILLATION_EFFICIENCY_BONUS = BUILDER
            .comment("The Efficiency that Nigredo, Albedo, Citrinitas, and Rubedo receive during distillation. A percentage of the distance between the actual device Efficiency and 100% Efficiency.")
            .defineInRange("houseOfAlchemyDistillationEfficiencyBonus", 50, 0, 100);

    private static final ForgeConfigSpec.BooleanValue CAN_AZOTH_DESTROY_BEDROCK = BUILDER
            .comment("Can Azoth destroy bedrock?")
            .define("canAzothDestroyBedrock", true);

    //----------------FIXATION PROCESS

    private static final ForgeConfigSpec.IntValue FIXATION_BASE_SLURRY_COST = BUILDER
            .comment("The amount of Academic Slurry, in mB, consumed to perform Fixation on a first-order Admixture.")
            .defineInRange("fixationBaseSlurryCost", 40, 10, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue FIXATION_SLURRY_COMPOUND_COST = BUILDER
            .comment("The percent cost increase over base that higher order Admixtures take to perform Fixation. This cost increase is multiplicative.")
            .defineInRange("fixationSlurryCompoundCost", 300, 10, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue FIXATION_FAILURE_REFUND = BUILDER
            .comment("The percent of the experience cost to perform Fixation that is reduced if the process fails.")
            .defineInRange("fixationFailureRefund", 70, 0, 100);

    //----------------ALEMBIC

    private static final ForgeConfigSpec.IntValue ALEMBIC_EFFICIENCY = BUILDER
            .comment("The baseline efficiency of an Alembic.")
            .defineInRange("alembicEfficiency", 30, 1, 100);

    private static final ForgeConfigSpec.IntValue ALEMBIC_OPERATION_TIME = BUILDER
            .comment("The time, in ticks, that it takes for an Alembic to process one object.")
            .defineInRange("alembicOperationTime", 200, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue ALEMBIC_MAXIMUM_GRIME = BUILDER
            .comment("The maximum Grime level of the Alembic. ")
            .defineInRange("alembicGrimeMaximum", 24000, 100, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue ALEMBIC_GRIME_ON_SUCCESS = BUILDER
            .comment("The amount of Grime generated by a dram of materia that successfully distills.")
            .defineInRange("alembicGrimeOnSuccess", 75, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue ALEMBIC_GRIME_ON_FAILURE = BUILDER
            .comment("The amount of Grime generated by a dram of materia that fails to distill.")
            .defineInRange("alembicGrimeOnFailure", 10, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue ALEMBIC_BONUS_WASTE = BUILDER
            .comment("How much higher, as a percent, that the Alembic's Grime meter is treated for the purpose of making Alchemical Waste.")
            .defineInRange("alembicBonusWaste", 100, 0, 900);

    private static final ForgeConfigSpec.IntValue ALEMBIC_TANK_CAPACITY = BUILDER
            .comment("How much fluid, in mB, an Alembic can hold.")
            .defineInRange("alembicTankCapacity", 4000, 1000, Integer.MAX_VALUE);

    //----------------DISTILLERY

    private static final ForgeConfigSpec.IntValue DISTILLERY_EFFICIENCY = BUILDER
            .comment("The baseline efficiency of a Distillery.")
            .defineInRange("distilleryEfficiency", 35, 1, 100);

    private static final ForgeConfigSpec.IntValue DISTILLERY_OPERATION_TIME = BUILDER
            .comment("The time, in ticks, that it takes for a Distillery to process one object.")
            .defineInRange("distilleryOperationTime", 160, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue DISTILLERY_MAXIMUM_GRIME = BUILDER
            .comment("The maximum Grime level of the Distillery. ")
            .defineInRange("distilleryGrimeMaximum", 40000, 100, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue DISTILLERY_GRIME_ON_SUCCESS = BUILDER
            .comment("The amount of Grime generated by a dram of materia that successfully distills.")
            .defineInRange("distilleryGrimeOnSuccess", 75, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue DISTILLERY_GRIME_ON_FAILURE = BUILDER
            .comment("The amount of Grime generated by a dram of materia that fails to distill.")
            .defineInRange("distilleryGrimeOnFailure", 10, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue DISTILLERY_TANK_CAPACITY = BUILDER
            .comment("How much fluid, in mB, a Distillery can hold.")
            .defineInRange("distilleryTankCapacity", 8000, 1000, Integer.MAX_VALUE);

    //----------------CENTRIFUGE

    private static final ForgeConfigSpec.IntValue CENTRIFUGE_EFFICIENCY = BUILDER
            .comment("The baseline efficiency of a Centrifuge.")
            .defineInRange("centrifugeEfficiency", 45, 1, 100);

    private static final ForgeConfigSpec.IntValue CENTRIFUGE_OPERATION_TIME = BUILDER
            .comment("The time, in ticks, that it takes for a Centrifuge to separate one admixture into component materia.")
            .defineInRange("centrifugeOperationTime", 160, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue CENTRIFUGE_MAXIMUM_GRIME = BUILDER
            .comment("The maximum Grime level of the Centrifuge. ")
            .defineInRange("centrifugeGrimeMaximum", 40000, 100, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue CENTRIFUGE_GRIME_ON_SUCCESS = BUILDER
            .comment("The amount of Grime generated by an admixture that successfully separates in a Centrifuge.")
            .defineInRange("centrifugeGrimeOnSuccess", 75, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue CENTRIFUGE_GRIME_ON_FAILURE = BUILDER
            .comment("The amount of Grime generated by an admixture that fails to separate in a Centrifuge.")
            .defineInRange("centrifugeGrimeOnFailure", 10, 0, Integer.MAX_VALUE);

    //----------------FUSERY

    private static final ForgeConfigSpec.IntValue FUSERY_EFFICIENCY = BUILDER
            .comment("The baseline efficiency of a Fusery.")
            .defineInRange("fuseryEfficiency", 45, 1, 100);

    private static final ForgeConfigSpec.IntValue FUSERY_OPERATION_TIME = BUILDER
            .comment("The time, in ticks, that it takes for a Fusery to make one admixture from its component materia.")
            .defineInRange("fuseryOperationTime", 160, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue FUSERY_MAXIMUM_GRIME = BUILDER
            .comment("The maximum Grime level of the Fusery. ")
            .defineInRange("fuseryGrimeMaximum", 40000, 100, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue FUSERY_GRIME_ON_SUCCESS = BUILDER
            .comment("The amount of Grime generated by an admixture that successfully combines in a Fusery.")
            .defineInRange("fuseryGrimeOnSuccess", 75, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue FUSERY_GRIME_ON_FAILURE = BUILDER
            .comment("The amount of Grime generated by an admixture that fails to combine in a Fusery.")
            .defineInRange("fuseryGrimeOnFailure", 10, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue FUSERY_TANK_CAPACITY = BUILDER
            .comment("The amount of Academic Slurry, in mB, the Fusery's internal tank can hold.")
            .defineInRange("fuseryTankCapacity", 4000, 500, Integer.MAX_VALUE);

    //----------------GRAND DISTILLERY

    private static final ForgeConfigSpec.IntValue GRAND_DISTILLERY_EFFICIENCY = BUILDER
            .comment("The baseline efficiency of a Grand Distillery.")
            .defineInRange("grandDistilleryEfficiency", 60, 1, 100);

    private static final ForgeConfigSpec.IntValue GRAND_DISTILLERY_MAXIMUM_GRIME = BUILDER
            .comment("The maximum Grime level of the Grand Distillery. ")
            .defineInRange("grandDistilleryGrimeMaximum", 64000, 100, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue GRAND_DISTILLERY_GRIME_ON_SUCCESS = BUILDER
            .comment("The amount of Grime generated by a dram of materia that successfully distills.")
            .defineInRange("grandDistilleryGrimeOnSuccess", 75, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue GRAND_DISTILLERY_GRIME_ON_FAILURE = BUILDER
            .comment("The amount of Grime generated by a dram of materia that fails to distill.")
            .defineInRange("grandDistilleryGrimeOnFailure", 10, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue GRAND_DISTILLERY_TANK_CAPACITY = BUILDER
            .comment("How much fluid, in mB, a Grand Distillery can hold.")
            .defineInRange("grandDistilleryTankCapacity", 32000, 1000, Integer.MAX_VALUE);

    //----------------GRAND CENTRIFUGE

    private static final ForgeConfigSpec.IntValue GRAND_CENTRIFUGE_EFFICIENCY = BUILDER
            .comment("The baseline efficiency of a Grand Distillery.")
            .defineInRange("grandCentrifugeEfficiency", 60, 1, 100);

    private static final ForgeConfigSpec.IntValue GRAND_CENTRIFUGE_MAXIMUM_GRIME = BUILDER
            .comment("The maximum Grime level of the Grand Distillery. ")
            .defineInRange("grandCentrifugeGrimeMaximum", 64000, 100, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue GRAND_CENTRIFUGE_GRIME_ON_SUCCESS = BUILDER
            .comment("The amount of Grime generated by a dram of materia that successfully distills.")
            .defineInRange("grandCentrifugeGrimeOnSuccess", 75, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue GRAND_CENTRIFUGE_GRIME_ON_FAILURE = BUILDER
            .comment("The amount of Grime generated by a dram of materia that fails to distill.")
            .defineInRange("grandCentrifugeGrimeOnFailure", 10, 0, Integer.MAX_VALUE);

    //----------------GRAND CENTRIFUGE

    private static final ForgeConfigSpec.IntValue GRAND_FUSERY_EFFICIENCY = BUILDER
            .comment("The baseline efficiency of a Grand Fusery.")
            .defineInRange("grandFuseryEfficiency", 60, 1, 100);

    private static final ForgeConfigSpec.IntValue GRAND_FUSERY_MAXIMUM_GRIME = BUILDER
            .comment("The maximum Grime level of the Grand Fusery.")
            .defineInRange("grandFuseryGrimeMaximum", 64000, 100, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue GRAND_FUSERY_GRIME_ON_SUCCESS = BUILDER
            .comment("The amount of Grime generated by an admixture that successfully combines in a Grand Fusery.")
            .defineInRange("grandFuseryGrimeOnSuccess", 75, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue GRAND_FUSERY_GRIME_ON_FAILURE = BUILDER
            .comment("The amount of Grime generated by an admixture that fails to combine in a Grand Fusery.")
            .defineInRange("grandFuseryGrimeOnFailure", 10, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue GRAND_FUSERY_TANK_CAPACITY = BUILDER
            .comment("The amount of Academic Slurry, in mB, the Grand Fusery's internal tank can hold.")
            .defineInRange("fuseryTankCapacity", 4000, 500, Integer.MAX_VALUE);

    //----------------ALCHEMICAL NEXUS

    private static final ForgeConfigSpec.IntValue ALCHEMICAL_NEXUS_TANK_CAPACITY = BUILDER
            .comment("The amount of Academic Slurry, in mB, the Alchemical Nexus's internal tank can hold.")
            .defineInRange("alchemicalNexusTankCapacity", 12000, 500, Integer.MAX_VALUE);

    //----------------CIRCLE OF POWER

    private static final ForgeConfigSpec.IntValue CIRCLE_OF_POWER_GEN_1_REAGENT = BUILDER
            .comment("How much FE/tick the Circle of Power generates when it has one reagent")
            .defineInRange("circlePowerGen1", 75, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue CIRCLE_OF_POWER_GEN_2_REAGENT = BUILDER
            .comment("How much FE/tick the Circle of Power generates when it has two reagents")
            .defineInRange("circlePowerGen2", 750, 2, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue CIRCLE_OF_POWER_GEN_3_REAGENT = BUILDER
            .comment("How much FE/tick the Circle of Power generates when it has three reagents")
            .defineInRange("circlePowerGen3", 7500, 3, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue CIRCLE_OF_POWER_GEN_4_REAGENT = BUILDER
            .comment("How much FE/tick the Circle of Power generates when it has all four reagents")
            .defineInRange("circlePowerGen4", 75000, 4, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.BooleanValue CIRCLE_OF_POWER_REPROCESSING_1_ETERNAL = BUILDER
            .comment("Should the first Circle of Power reagent (Grains of Quicksilver) function forever without requiring reprocessing?")
            .define("circlePowerReprocessing1Eternal", false);

    private static final ForgeConfigSpec.BooleanValue CIRCLE_OF_POWER_REPROCESSING_2_ETERNAL = BUILDER
            .comment("Should the second Circle of Power reagent (Focusing Catalyst) function forever without requiring reprocessing?")
            .define("circlePowerReprocessing2Eternal", false);

    private static final ForgeConfigSpec.BooleanValue CIRCLE_OF_POWER_REPROCESSING_3_ETERNAL = BUILDER
            .comment("Should the third Circle of Power reagent (Amplifying Prism) function forever without requiring reprocessing?")
            .define("circlePowerReprocessing3Eternal", true);

    private static final ForgeConfigSpec.BooleanValue CIRCLE_OF_POWER_REPROCESSING_4_ETERNAL = BUILDER
            .comment("Should the last Circle of Power reagent (Auxiliary Circle Array) function forever without requiring reprocessing?")
            .define("circlePowerReprocessing4Eternal", true);

    private static final ForgeConfigSpec.IntValue CIRCLE_OF_POWER_BUFFER = BUILDER
            .comment("How many ticks of activity the Circle of Power stores at once")
            .defineInRange("circlePowerBuffer", 3, 1, 72000);

    //----------------CIRCLE OF TOIL

    private static final ForgeConfigSpec.IntValue CIRCLE_OF_TOIL_GEN = BUILDER
            .comment("How much FE/tick the Circle of Toil generates at max speed")
            .defineInRange("circleToilGen", 20, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue CIRCLE_OF_TOIL_BUFFER = BUILDER
            .comment("How many ticks of activity the Circle of Toil stores at once")
            .defineInRange("circleToilBuffer", 3, 1, 72000);

    //----------------CIRCLE OF FABRICATION

    private static final ForgeConfigSpec.IntValue CIRCLE_FABRICATION_TANK_CAPACITY = BUILDER
            .comment("How much fluid, in mB, a Circle of Fabrication can hold")
            .defineInRange("circleFabricationTankCapacity", 8000, 1000, Integer.MAX_VALUE);

    //----------------GRAND CIRCLE OF FABRICATION

    private static final ForgeConfigSpec.IntValue GRAND_CIRCLE_FABRICATION_TANK_CAPACITY = BUILDER
            .comment("How much fluid, in mB, a Grand Circle of Fabrication can hold")
            .defineInRange("GrandCircleFabricationTankCapacity", 32000, 1000, Integer.MAX_VALUE);

    //----------------MATERIA JAR

    private static final ForgeConfigSpec.IntValue MATERIA_JAR_ESSENTIA_CAPACITY = BUILDER
            .comment("How much of one type of Essentia can be stored inside of a Materia Jar.")
            .defineInRange("materiaJarEssentiaCapacity", 720, 64, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue MATERIA_JAR_ADMIXTURE_CAPACITY = BUILDER
            .comment("How much of one type of Admixture can be stored inside of a Materia Jar.")
            .defineInRange("materiaJarAdmixtureCapacity", 360, 64, Integer.MAX_VALUE);

    //----------------MATERIA VESSEL

    private static final ForgeConfigSpec.IntValue MATERIA_VESSEL_ESSENTIA_CAPACITY = BUILDER
            .comment("How much of one type of Essentia can be stored inside of a Materia Vessel.")
            .defineInRange("materiaVesselEssentiaCapacity", 3600, 64, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue MATERIA_VESSEL_ADMIXTURE_CAPACITY = BUILDER
            .comment("How much of one type of Admixture can be stored inside of a Materia Vessel.")
            .defineInRange("materiaVesselAdmixtureCapacity", 1800, 64, Integer.MAX_VALUE);

    //----------------GENERAL ACTUATORS

    private static final ForgeConfigSpec.IntValue ACTUATOR_SINGLE_SUPPLIED_PERIOD = BUILDER
            .comment("The amount of time, in ticks, that actuators take in between drawing Eldrin power or consuming materia units when only one of the two is present.")
            .defineInRange("actuatorSingleSuppliedPeriod", 300, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue ACTUATOR_DOUBLE_SUPPLIED_PERIOD = BUILDER
            .comment("The amount of time, in ticks, that actuators take in between drawing Eldrin power and consuming materia units when both are present.")
            .defineInRange("actuatorDoubleSuppliedPeriod", 1200, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue ACTUATOR_MATERIA_BUFFER_MAXIMUM = BUILDER
            .comment("The amount of materia units that an actuator can store.")
            .defineInRange("actuatorMateriaBufferMaximum", 400, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue ACTUATOR_MATERIA_UNITS_PER_DRAM = BUILDER
            .comment("The number of materia units that an Actuator gets from a single dram of materia")
            .defineInRange("actuatorMateriaUnitsPerDram", 40, 1, Integer.MAX_VALUE);

    //----------------PROTO ACTUATOR

    private static final ForgeConfigSpec.IntValue PROTO_ACTUATOR_FE_COST = BUILDER
            .comment("The amount of FE per tick that must be supplied to a Proto-Actuator.")
            .defineInRange("protoActuatorFECost", 20, 1, Integer.MAX_VALUE);

    //----------------DELUGE PURIFIER

    private static final ForgeConfigSpec.IntValue DELUGE_PURIFIER_TANK_CAPACITY = BUILDER
            .comment("The amount of Water and Steam, in mB, the Deluge Purifier's internal tanks can hold.")
            .defineInRange("delugePurifierTankCapacity", 5000, 500, Integer.MAX_VALUE);

    //----------------INFERNO ENGINE

    private static final ForgeConfigSpec.IntValue INFERNO_ENGINE_TANK_CAPACITY = BUILDER
            .comment("The amount of Smoke, in mB, the Inferno Engine's internal tank can hold.")
            .defineInRange("infernoEngineTankCapacity", 5000, 500, Integer.MAX_VALUE);

    //----------------QUAKE REFINERY

    private static final ForgeConfigSpec.IntValue QUAKE_REFINERY_SAND_CAPACITY = BUILDER
            .comment("The amount of sand that can be stored in the Quake Refinery's internal buffer.")
            .defineInRange("quakeRefinerySandCapacity", 16000, 500, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue QUAKE_REFINERY_GRIME_CAPACITY = BUILDER
            .comment("The amount of Grime that can be stored in the Quake Refinery's internal buffer.")
            .defineInRange("quakeRefineryGrimeCapacity", 128000, 500, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue QUAKE_REFINERY_RAREFIED_RATE = BUILDER
            .comment("What percentage of Grime reduced by a Quake Refinery becomes Rarefied Waste instead of Alchemical Waste.")
            .defineInRange("quakeRefineryRarefiedRate", 40, 1, 100);

    //----------------GALE PRESSURIZER

    private static final ForgeConfigSpec.IntValue GALE_PRESSURIZER_TANK_CAPACITY = BUILDER
            .comment("The amount of Smoke and Steam, in mB, the Gale Pressurizer's internal tanks can hold.")
            .defineInRange("galePressurizerTankCapacity", 5000, 500, Integer.MAX_VALUE);

    //----------------OCCULT MATRIX

    private static final ForgeConfigSpec.IntValue OCCULT_MATRIX_TANK_CAPACITY = BUILDER
            .comment("The amount of Academic Slurry, in mB, the Gale Pressurizer's internal tanks can hold.")
            .defineInRange("occultMatrixTankCapacity", 72000, 500, Integer.MAX_VALUE);

    //----------------COLORING CAULDRON

    private static final ForgeConfigSpec.IntValue COLORING_CAULDRON_BASE_OPERATION_TIME = BUILDER
            .comment("The amount of time, in ticks, that it takes for a Coloring Cauldron with one dye to color an item. This time is exponentially reduced with more dyes down to a quarter at 15 dyes.")
            .defineInRange("coloringCauldronBaseOperationTime", 300, 10, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue COLORING_CAULDRON_POSITIVE_CHARGES = BUILDER
            .comment("The number of items that a Coloring Cauldron can color per unit of dye when in positive mode.")
            .defineInRange("coloringCauldronPositiveCharges", 3, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue COLORING_CAULDRON_NEGATIVE_CHARGES = BUILDER
            .comment("The number of items that a Coloring Cauldron can color per unit of dye when in positive mode.")
            .defineInRange("coloringCauldronNegativeCharges", 5, 1, Integer.MAX_VALUE);

    //----------------VARIEGATOR

    private static final ForgeConfigSpec.IntValue VARIEGATOR_OPERATION_TIME_SLOW = BUILDER
            .comment("The amount of time, in ticks, a Variegator requires to dye something if there is insufficient dye/Admixture of Color.")
            .defineInRange("variegatorOperationTimeSlow", 300, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue VARIEGATOR_OPERATION_TIME_FAST = BUILDER
            .comment("The amount of time, in ticks, a Variegator requires to dye something if appropriate dye/Admixture of Color is provided.")
            .defineInRange("variegatorOperationTimeFast", 40, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue VARIEGATOR_MATCHED_COLOR_TIME_DISCOUNT = BUILDER
            .comment("What percentage the crafting time is reduced by if both Admixture of Color and a full bar of the appropriate dye are present. This is linearly reduced with the fill of the dye gauge.")
            .defineInRange("variegatorMatchedColorTimeDiscount", 80, 0, 99);

    private static final ForgeConfigSpec.IntValue VARIEGATOR_MAX_DYE = BUILDER
            .comment("The number of units each of the Variegator's dye gauges can hold.")
            .defineInRange("variegatorMaxDye", 250, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue VARIEGATOR_DYE_PER_ITEM = BUILDER
            .comment("How many units of dye each dye item inserted into the Variegator is worth.")
            .defineInRange("variegatorDyePerItem", 10, 1, 64);

    private static final ForgeConfigSpec.IntValue VARIEGATOR_MAX_ADMIXTURE = BUILDER
            .comment("The number of units the Variegator's Admixture of Color gauge can hold.")
            .defineInRange("variegatorMaxAdmixture", 600, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue VARIEGATOR_ADMIXTURE_PER_ITEM = BUILDER
            .comment("How many units of dye each dram of Admixture of Color inserted into the Variegator is worth.")
            .defineInRange("variegatorAdmixturePerItem", 15, 1, 64);

    //----------------CONJURER

    private static final ForgeConfigSpec.IntValue CONJURER_MATERIA_CAPACITY = BUILDER
            .comment("The maximum capacity of the Conjurer's materia gauge.")
            .defineInRange("conjurerMateriaCapacity", 100, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue CONJURER_POINTS_PER_DRAM = BUILDER
            .comment("The number of points that a single dram of materia adds to the materia gauge.")
            .defineInRange("conjurerPointsPerDram", 4, 1, Integer.MAX_VALUE);

    //----------------SKYWRATH ALTAR

    private static final ForgeConfigSpec.IntValue SKYWRATH_ALTAR_FE_RECHARGE_PERCENTAGE = BUILDER
            .comment("What percentage a Skywrath Altar will recharge an object's FE gauge to. Only used if this value would be less than the recharge limit below.")
            .defineInRange("skywrathAltarFEChargePercentage", 50, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue SKYWRATH_ALTAR_FE_RECHARGE_LIMIT = BUILDER
            .comment("The maximum amount of FE a Skywrath Altar will recharge an object's FE gauge by. Only used if this value would be greater than the recharge percentage above.")
            .defineInRange("skywrathAltarFEChargeLimit", 30000, 1, Integer.MAX_VALUE);

    //----------------SKYWRATH CONDENSER

    private static final ForgeConfigSpec.IntValue SKYWRATH_CONDENSER_MATERIA_UNITS_PER_DRAM = BUILDER
            .comment("The number of materia units that a Skywrath Condenser gets from a single dram of materia")
            .defineInRange("skywrathCondenserMateriaUnitsPerDram", 40, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue SKYWRATH_CONDENSER_LIGHTNING_TRIGGER_COST = BUILDER
            .comment("How many materia units are consumed by a Skywrath Altar when a craft is triggered by Lightning Damage")
            .defineInRange("skywrathCondenserLightningTriggerCost", 30, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue SKYWRATH_CONDENSER_REDSTONE_TRIGGER_COST = BUILDER
            .comment("How many materia units are consumed by a Skywrath Altar when a craft is triggered by a redstone signal")
            .defineInRange("skywrathCondenserRedstoneTriggerCost", 120, 1, Integer.MAX_VALUE);

    //----------------ASTRAL OBSERVER

    private static final ForgeConfigSpec.IntValue ASTRAL_OBSERVER_LUMIN_GAIN_STANDARD = BUILDER
            .comment("How many Lumins an object gains when using a standard glass lens during a correct celestial phase")
            .defineInRange("astralObserverLuminGainStandard", 20, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue ASTRAL_OBSERVER_LUMIN_GAIN_CLOISTER = BUILDER
            .comment("How many Lumins an object gains when using a cloister lens during a correct celestial phase")
            .defineInRange("astralObserverLuminGainCloister", 12, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue ASTRAL_OBSERVER_LUMIN_GAIN_FARSIGHT = BUILDER
            .comment("How many Lumins an object gains when using a standard glass lens during a correct celestial phase")
            .defineInRange("astralObserverLuminGainFarsight", 6, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue ASTRAL_OBSERVER_LUMIN_LOSS = BUILDER
            .comment("How many Lumins an object loses when using a standard glass lens during incorrect celestial phases")
            .defineInRange("astralObserverLuminLoss", 5, 1, Integer.MAX_VALUE);

    //----------------ACID BASIN

    private static final ForgeConfigSpec.IntValue ACID_BASIN_TANK_CAPACITY = BUILDER
            .comment("The amount of Water and Steam, in mB, both of the Acid Basin's internal tanks can hold.")
            .defineInRange("acidBasinTankCapacity", 5000, 1, Integer.MAX_VALUE);

    //----------------MATERIA MANIFEST

    private static final ForgeConfigSpec.IntValue MATERIA_MANIFEST_SIZE_CONSTRAINT = BUILDER
            .comment("The maximum length in any one axis that the Materia Manifest will allow from a Rune of Marking Pair.")
            .defineInRange("materiaManifestSizeConstraint", 40, 1, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue MATERIA_MANIFEST_DISTANCE_LIMIT = BUILDER
            .comment("The maximum distance from the center of the Rune of Marking Pair that a Materia Manifest can be. Set to 0 for no limit.")
            .defineInRange("materiaManifestDistanceLimit", 150, 0, Integer.MAX_VALUE);

    private static final ForgeConfigSpec.IntValue MATERIA_MANIFEST_DEFAULT_RANGE = BUILDER
            .comment("The default cuboid range that a Materia Manifest searches for containers in. The center block is not counted as part of this squadius.")
            .defineInRange("materiaManifestDefaultRange", 8, 1, Integer.MAX_VALUE);

    //ITEMS
    private static final ForgeConfigSpec.IntValue SLUMBERING_IDOL_RANGE = BUILDER
            .comment("The default cuboid range that a Slumbering Idol will slaughter Phantoms in.")
            .defineInRange("slumberingIdolRange", 64, 16, 1024);

    //GNOSTIC ORB
    private static final ForgeConfigSpec.ConfigValue<List<?>> GNOSTIC_ORB_PROPHECY_BLACKLIST = BUILDER
            .comment("A comma separated list of English admixture names. Disables Prophecies of that type of materia from being started. Use the name alone without a prefix, e.g. disaster instead of admixture_disaster.")
            .defineList("gnosticOrbProphecyBlacklist", Arrays.asList(), (e) -> {
                return true;
            });

    //WISDOM BLACKLISTS
    private static final List<String> WISDOM_BLACKLIST_DAMAGE_DEFAULTS = new ArrayList<>();
    private static final List<String> WISDOM_BLACKLIST_DELAY_DEFAULTS = new ArrayList<>();
    private static final List<String> WISDOM_BLACKLIST_DURATION_DEFAULTS = new ArrayList<>();
    private static final List<String> WISDOM_BLACKLIST_LESSER_MAGNITUDE_DEFAULTS = new ArrayList<>();
    private static final List<String> WISDOM_BLACKLIST_MAGNITUDE_DEFAULTS = new ArrayList<>();
    private static final List<String> WISDOM_BLACKLIST_RADIUS_DEFAULTS = new ArrayList<>();
    private static final List<String> WISDOM_BLACKLIST_RANGE_DEFAULTS = new ArrayList<>();
    private static final List<String> WISDOM_BLACKLIST_SPEED_DEFAULTS = new ArrayList<>();
    static {
        WISDOM_BLACKLIST_MAGNITUDE_DEFAULTS.add("mna:components/shield");
        WISDOM_BLACKLIST_MAGNITUDE_DEFAULTS.add("mna:components/simulacrum");
    }

    private static final ForgeConfigSpec.ConfigValue<List<?>> WISDOM_BLACKLIST_DAMAGE = BUILDER
            .comment("A comma separated list of component registry names that ignore boosts to Damage from the Wisdom Stones.")
            .defineList("wisdomBlacklistDamage", WISDOM_BLACKLIST_DAMAGE_DEFAULTS, (e) -> {
                return true;
            });

    private static final ForgeConfigSpec.ConfigValue<List<?>> WISDOM_BLACKLIST_DELAY = BUILDER
            .comment("A comma separated list of component registry names that ignore boosts to Delay from the Wisdom Stones.")
            .defineList("wisdomBlacklistDelay", WISDOM_BLACKLIST_DELAY_DEFAULTS, (e) -> {
                return true;
            });

    private static final ForgeConfigSpec.ConfigValue<List<?>> WISDOM_BLACKLIST_DURATION = BUILDER
            .comment("A comma separated list of component registry names that ignore boosts to Duration from the Wisdom Stones.")
            .defineList("wisdomBlacklistDuration", WISDOM_BLACKLIST_DURATION_DEFAULTS, (e) -> {
                return true;
            });

    private static final ForgeConfigSpec.ConfigValue<List<?>> WISDOM_BLACKLIST_LESSER_MAGNITUDE = BUILDER
            .comment("A comma separated list of component registry names that ignore boosts to Lesser Magnitude from the Wisdom Stones.")
            .defineList("wisdomBlacklistLesserMagnitude", WISDOM_BLACKLIST_LESSER_MAGNITUDE_DEFAULTS, (e) -> {
                return true;
            });

    private static final ForgeConfigSpec.ConfigValue<List<?>> WISDOM_BLACKLIST_MAGNITUDE = BUILDER
            .comment("A comma separated list of component registry names that ignore boosts to Magnitude from the Wisdom Stones.")
            .defineList("wisdomBlacklistMagnitude", WISDOM_BLACKLIST_MAGNITUDE_DEFAULTS, (e) -> {
                return true;
            });

    private static final ForgeConfigSpec.ConfigValue<List<?>> WISDOM_BLACKLIST_RADIUS = BUILDER
            .comment("A comma separated list of component registry names that ignore boosts to Radius from the Wisdom Stones.")
            .defineList("wisdomBlacklistRadius", WISDOM_BLACKLIST_RADIUS_DEFAULTS, (e) -> {
                return true;
            });

    private static final ForgeConfigSpec.ConfigValue<List<?>> WISDOM_BLACKLIST_RANGE = BUILDER
            .comment("A comma separated list of component registry names that ignore boosts to Range from the Wisdom Stones.")
            .defineList("wisdomBlacklistRange", WISDOM_BLACKLIST_RANGE_DEFAULTS, (e) -> {
                return true;
            });

    private static final ForgeConfigSpec.ConfigValue<List<?>> WISDOM_BLACKLIST_SPEED = BUILDER
            .comment("A comma separated list of component registry names that ignore boosts to Speed from the Wisdom Stones.")
            .defineList("wisdomBlacklistSpeed", WISDOM_BLACKLIST_SPEED_DEFAULTS, (e) -> {
                return true;
            });

    public static final ForgeConfigSpec SPEC = BUILDER.build();

    public static int
        grimePerWaste,
        grimePenaltyPoint,
        fluidPerXPPoint,
        constructStudyExperienceSimple,
        constructStudyExperienceAdvanced,
        constructStudyExperienceMaster,
        houseOfAlchemyDistillationEfficiencyBonus,
        fixationBaseSlurryCost,
        fixationSlurryCompoundCost,
        fixationFailureRefund,
        alembicEfficiency,
        alembicOperationTime,
        alembicMaximumGrime,
        alembicGrimeOnSuccess,
        alembicGrimeOnFailure,
        alembicBonusWaste,
        alembicTankCapacity,
        distilleryEfficiency,
        distilleryOperationTime,
        distilleryMaximumGrime,
        distilleryGrimeOnSuccess,
        distilleryGrimeOnFailure,
        distilleryTankCapacity,
        grandDistilleryEfficiency,
        grandDistilleryMaximumGrime,
        grandDistilleryGrimeOnSuccess,
        grandDistilleryGrimeOnFailure,
        grandDistilleryTankCapacity,
        grandCentrifugeEfficiency,
        grandCentrifugeMaximumGrime,
        grandCentrifugeGrimeOnSuccess,
        grandCentrifugeGrimeOnFailure,
        grandFuseryEfficiency,
        grandFuseryMaximumGrime,
        grandFuseryGrimeOnSuccess,
        grandFuseryGrimeOnFailure,
        grandFuseryTankCapacity,
        centrifugeEfficiency,
        centrifugeOperationTime,
        centrifugeMaximumGrime,
        centrifugeGrimeOnSuccess,
        centrifugeGrimeOnFailure,
        fuseryEfficiency,
        fuseryOperationTime,
        fuseryMaximumGrime,
        fuseryGrimeOnSuccess,
        fuseryGrimeOnFailure,
        fuseryTankCapacity,
        alchemicalNexusTankCapacity,
        circlePowerGen1Reagent,
        circlePowerGen2Reagent,
        circlePowerGen3Reagent,
        circlePowerGen4Reagent,
        circlePowerBuffer,
        circleToilGen,
        circleToilBuffer,
        circleFabricationTankCapacity,
        grandCircleFabricationTankCapacity,
        materiaJarEssentiaCapacity,
        materiaJarAdmixtureCapacity,
        materiaVesselEssentiaCapacity,
        materiaVesselAdmixtureCapacity,
        actuatorSingleSuppliedPeriod,
        actuatorDoubleSuppliedPeriod,
        actuatorMateriaBufferMaximum,
        actuatorMateriaUnitsPerDram,
        protoActuatorFECost,
        delugePurifierTankCapacity,
        infernoEngineTankCapacity,
        quakeRefinerySandCapacity,
        quakeRefineryGrimeCapacity,
        quakeRefineryRarefiedRate,
        galePressurizerTankCapacity,
        occultMatrixTankCapacity,
        coloringCauldronBaseOperationTime,
        coloringCauldronPositiveCharges,
        coloringCauldronNegativeCharges,
        variegatorOperationTimeSlow,
        variegatorOperationTimeFast,
        variegatorMatchedColorTimeDiscount,
        variegatorMaxDye,
        variegatorDyePerItem,
        variegatorMaxAdmixture,
        variegatorAdmixturePerItem,
        conjurerMateriaCapacity,
        conjurerPointsPerDram,
        skywrathAltarFERechargePercentage,
        skywrathAltarFERechargeLimit,
        skywrathCondenserMateriaUnitsPerDram,
        skywrathCondenserLightningTriggerCost,
        skywrathCondenserRedstoneTriggerCost,
        astralObserverLuminGainStandard,
        astralObserverLuminGainCloister,
        astralObserverLuminGainFarsight,
        astralObserverLuminLoss,
        acidBasinTankCapacity,
        materiaManifestSizeConstraint,
        materiaManifestDistanceLimit,
        materiaManifestDefaultRange,
        slumberingIdolRange;
    public static boolean
        canAzothDestroyBedrock,
        circlePowerReprocessing1Eternal,
        circlePowerReprocessing2Eternal,
        circlePowerReprocessing3Eternal,
        circlePowerReprocessing4Eternal;
    public static HashSet<? extends String>
        gnosticOrbProphecyBlacklist,
        wisdomBlacklistDamage,
        wisdomBlacklistDelay,
        wisdomBlacklistDuration,
        wisdomBlacklistLesserMagnitude,
        wisdomBlacklistMagnitude,
        wisdomBlacklistRadius,
        wisdomBlacklistRange,
        wisdomBlacklistSpeed;

    private static boolean validateItemName(final Object obj)
    {
        return obj instanceof final String itemName && ForgeRegistries.ITEMS.containsKey(new ResourceLocation(itemName));
    }

    @SubscribeEvent
    public static void onModConfigEvent(ModConfigEvent event) {
        if (event.getConfig().getSpec() == SPEC) {
            bakeConfig();
        }
    }

    @SubscribeEvent
    static void onLoad(final ModConfigEvent event)
    {
        bakeConfig();
    }

    private static void bakeConfig() {
        gnosticOrbProphecyBlacklist = new HashSet(GNOSTIC_ORB_PROPHECY_BLACKLIST.get());

        wisdomBlacklistDamage = new HashSet(WISDOM_BLACKLIST_DAMAGE.get());
        wisdomBlacklistDelay = new HashSet(WISDOM_BLACKLIST_DELAY.get());
        wisdomBlacklistDuration = new HashSet(WISDOM_BLACKLIST_DURATION.get());
        wisdomBlacklistLesserMagnitude = new HashSet(WISDOM_BLACKLIST_LESSER_MAGNITUDE.get());
        wisdomBlacklistMagnitude = new HashSet(WISDOM_BLACKLIST_MAGNITUDE.get());
        wisdomBlacklistRadius = new HashSet(WISDOM_BLACKLIST_RADIUS.get());
        wisdomBlacklistRange = new HashSet(WISDOM_BLACKLIST_RANGE.get());
        wisdomBlacklistSpeed = new HashSet(WISDOM_BLACKLIST_SPEED.get());

        grimePerWaste = GRIME_PER_WASTE.get();
        grimePenaltyPoint = GRIME_PENALTY_POINT.get();
        fluidPerXPPoint = FLUID_PER_XP_POINT.get();
        constructStudyExperienceSimple = CONSTRUCT_STUDY_EXPERIENCE_SIMPLE.get();
        constructStudyExperienceAdvanced = CONSTRUCT_STUDY_EXPERIENCE_ADVANCED.get();
        constructStudyExperienceMaster = CONSTRUCT_STUDY_EXPERIENCE_MASTER.get();
        houseOfAlchemyDistillationEfficiencyBonus = HOUSE_OF_ALCHEMY_DISTILLATION_EFFICIENCY_BONUS.get();
        canAzothDestroyBedrock = CAN_AZOTH_DESTROY_BEDROCK.get();
        fixationBaseSlurryCost = FIXATION_BASE_SLURRY_COST.get();
        fixationSlurryCompoundCost = FIXATION_SLURRY_COMPOUND_COST.get();
        fixationFailureRefund = FIXATION_FAILURE_REFUND.get();
        alembicEfficiency = ALEMBIC_EFFICIENCY.get();
        alembicOperationTime = ALEMBIC_OPERATION_TIME.get();
        alembicMaximumGrime = ALEMBIC_MAXIMUM_GRIME.get();
        alembicGrimeOnSuccess = ALEMBIC_GRIME_ON_SUCCESS.get();
        alembicGrimeOnFailure = ALEMBIC_GRIME_ON_FAILURE.get();
        alembicBonusWaste = ALEMBIC_BONUS_WASTE.get();
        alembicTankCapacity = ALEMBIC_TANK_CAPACITY.get();
        distilleryEfficiency = DISTILLERY_EFFICIENCY.get();
        distilleryOperationTime = DISTILLERY_OPERATION_TIME.get();
        distilleryMaximumGrime = DISTILLERY_MAXIMUM_GRIME.get();
        distilleryGrimeOnSuccess = DISTILLERY_GRIME_ON_SUCCESS.get();
        distilleryGrimeOnFailure = DISTILLERY_GRIME_ON_FAILURE.get();
        distilleryTankCapacity = DISTILLERY_TANK_CAPACITY.get();
        centrifugeEfficiency = CENTRIFUGE_EFFICIENCY.get();
        centrifugeOperationTime = CENTRIFUGE_OPERATION_TIME.get();
        centrifugeMaximumGrime = CENTRIFUGE_MAXIMUM_GRIME.get();
        centrifugeGrimeOnSuccess = CENTRIFUGE_GRIME_ON_SUCCESS.get();
        centrifugeGrimeOnFailure = CENTRIFUGE_GRIME_ON_FAILURE.get();
        fuseryEfficiency = FUSERY_EFFICIENCY.get();
        fuseryOperationTime = FUSERY_OPERATION_TIME.get();
        fuseryMaximumGrime = FUSERY_MAXIMUM_GRIME.get();
        fuseryGrimeOnSuccess = FUSERY_GRIME_ON_SUCCESS.get();
        fuseryGrimeOnFailure = FUSERY_GRIME_ON_FAILURE.get();
        fuseryTankCapacity = FUSERY_TANK_CAPACITY.get();
        grandDistilleryEfficiency = GRAND_DISTILLERY_EFFICIENCY.get();
        grandDistilleryMaximumGrime = GRAND_DISTILLERY_MAXIMUM_GRIME.get();
        grandDistilleryGrimeOnSuccess = GRAND_DISTILLERY_GRIME_ON_SUCCESS.get();
        grandDistilleryGrimeOnFailure = GRAND_DISTILLERY_GRIME_ON_FAILURE.get();
        grandDistilleryTankCapacity = GRAND_DISTILLERY_TANK_CAPACITY.get();
        grandCentrifugeEfficiency = GRAND_CENTRIFUGE_EFFICIENCY.get();
        grandCentrifugeMaximumGrime = GRAND_CENTRIFUGE_MAXIMUM_GRIME.get();
        grandCentrifugeGrimeOnSuccess = GRAND_CENTRIFUGE_GRIME_ON_SUCCESS.get();
        grandCentrifugeGrimeOnFailure = GRAND_CENTRIFUGE_GRIME_ON_FAILURE.get();
        grandFuseryEfficiency = GRAND_FUSERY_EFFICIENCY.get();
        grandFuseryMaximumGrime = GRAND_FUSERY_MAXIMUM_GRIME.get();
        grandFuseryGrimeOnSuccess = GRAND_FUSERY_GRIME_ON_SUCCESS.get();
        grandFuseryGrimeOnFailure = GRAND_FUSERY_GRIME_ON_FAILURE.get();
        grandFuseryTankCapacity = GRAND_FUSERY_TANK_CAPACITY.get();
        alchemicalNexusTankCapacity = ALCHEMICAL_NEXUS_TANK_CAPACITY.get();
        circlePowerGen1Reagent = CIRCLE_OF_POWER_GEN_1_REAGENT.get();
        circlePowerGen2Reagent = CIRCLE_OF_POWER_GEN_2_REAGENT.get();
        circlePowerGen3Reagent = CIRCLE_OF_POWER_GEN_3_REAGENT.get();
        circlePowerGen4Reagent = CIRCLE_OF_POWER_GEN_4_REAGENT.get();
        circlePowerReprocessing1Eternal = CIRCLE_OF_POWER_REPROCESSING_1_ETERNAL.get();
        circlePowerReprocessing2Eternal = CIRCLE_OF_POWER_REPROCESSING_2_ETERNAL.get();
        circlePowerReprocessing3Eternal = CIRCLE_OF_POWER_REPROCESSING_3_ETERNAL.get();
        circlePowerReprocessing4Eternal = CIRCLE_OF_POWER_REPROCESSING_4_ETERNAL.get();
        circlePowerBuffer = CIRCLE_OF_POWER_BUFFER.get();
        circleToilGen = CIRCLE_OF_TOIL_GEN.get();
        circleToilBuffer = CIRCLE_OF_TOIL_BUFFER.get();
        circleFabricationTankCapacity = CIRCLE_FABRICATION_TANK_CAPACITY.get();
        grandCircleFabricationTankCapacity = GRAND_CIRCLE_FABRICATION_TANK_CAPACITY.get();
        materiaJarEssentiaCapacity = MATERIA_JAR_ESSENTIA_CAPACITY.get();
        materiaJarAdmixtureCapacity = MATERIA_JAR_ADMIXTURE_CAPACITY.get();
        materiaVesselEssentiaCapacity = MATERIA_VESSEL_ESSENTIA_CAPACITY.get();
        materiaVesselAdmixtureCapacity = MATERIA_VESSEL_ADMIXTURE_CAPACITY.get();
        actuatorSingleSuppliedPeriod = ACTUATOR_SINGLE_SUPPLIED_PERIOD.get();
        actuatorDoubleSuppliedPeriod = ACTUATOR_DOUBLE_SUPPLIED_PERIOD.get();
        actuatorMateriaBufferMaximum = ACTUATOR_MATERIA_BUFFER_MAXIMUM.get();
        actuatorMateriaUnitsPerDram = ACTUATOR_MATERIA_UNITS_PER_DRAM.get();
        protoActuatorFECost = PROTO_ACTUATOR_FE_COST.get();
        delugePurifierTankCapacity = DELUGE_PURIFIER_TANK_CAPACITY.get();
        infernoEngineTankCapacity = INFERNO_ENGINE_TANK_CAPACITY.get();
        quakeRefinerySandCapacity = QUAKE_REFINERY_SAND_CAPACITY.get();
        quakeRefineryGrimeCapacity = QUAKE_REFINERY_GRIME_CAPACITY.get();
        quakeRefineryRarefiedRate = QUAKE_REFINERY_RAREFIED_RATE.get();
        galePressurizerTankCapacity = GALE_PRESSURIZER_TANK_CAPACITY.get();
        occultMatrixTankCapacity = OCCULT_MATRIX_TANK_CAPACITY.get();
        coloringCauldronBaseOperationTime = COLORING_CAULDRON_BASE_OPERATION_TIME.get();
        coloringCauldronPositiveCharges = COLORING_CAULDRON_POSITIVE_CHARGES.get();
        coloringCauldronNegativeCharges = COLORING_CAULDRON_NEGATIVE_CHARGES.get();
        variegatorOperationTimeSlow = VARIEGATOR_OPERATION_TIME_SLOW.get();
        variegatorOperationTimeFast = VARIEGATOR_OPERATION_TIME_FAST.get();
        variegatorMatchedColorTimeDiscount = VARIEGATOR_MATCHED_COLOR_TIME_DISCOUNT.get();
        variegatorMaxDye = VARIEGATOR_MAX_DYE.get();
        variegatorDyePerItem = VARIEGATOR_DYE_PER_ITEM.get();
        variegatorMaxAdmixture = VARIEGATOR_MAX_ADMIXTURE.get();
        variegatorAdmixturePerItem = VARIEGATOR_ADMIXTURE_PER_ITEM.get();
        conjurerMateriaCapacity = CONJURER_MATERIA_CAPACITY.get();
        conjurerPointsPerDram = CONJURER_POINTS_PER_DRAM.get();
        skywrathAltarFERechargePercentage = SKYWRATH_ALTAR_FE_RECHARGE_PERCENTAGE.get();
        skywrathAltarFERechargeLimit = SKYWRATH_ALTAR_FE_RECHARGE_LIMIT.get();
        skywrathCondenserMateriaUnitsPerDram = SKYWRATH_CONDENSER_MATERIA_UNITS_PER_DRAM.get();
        skywrathCondenserLightningTriggerCost = SKYWRATH_CONDENSER_LIGHTNING_TRIGGER_COST.get();
        skywrathCondenserRedstoneTriggerCost = SKYWRATH_CONDENSER_REDSTONE_TRIGGER_COST.get();
        astralObserverLuminGainStandard = ASTRAL_OBSERVER_LUMIN_GAIN_STANDARD.get();
        astralObserverLuminGainCloister = ASTRAL_OBSERVER_LUMIN_GAIN_CLOISTER.get();
        astralObserverLuminGainFarsight = ASTRAL_OBSERVER_LUMIN_GAIN_FARSIGHT.get();
        astralObserverLuminLoss = ASTRAL_OBSERVER_LUMIN_LOSS.get();
        acidBasinTankCapacity = ACID_BASIN_TANK_CAPACITY.get();
        materiaManifestSizeConstraint = MATERIA_MANIFEST_SIZE_CONSTRAINT.get();
        materiaManifestDistanceLimit = MATERIA_MANIFEST_DISTANCE_LIMIT.get();
        materiaManifestDefaultRange = MATERIA_MANIFEST_DEFAULT_RANGE.get();
        slumberingIdolRange = SLUMBERING_IDOL_RANGE.get();
    }
}
