package com.aranaira.magichem.foundation.enums;

public enum GrandDistilleryRouterType {
    NONE,
    DAIS,
    BACK,
    PLUG_FRONT_LEFT,
    PLUG_FRONT_RIGHT,
    PLUG_MID_LEFT,
    PLUG_MID_RIGHT,
    PLUG_BACK_LEFT,
    PLUG_BACK_RIGHT,
    TANK_MID_FRONT_CENTER,
    TANK_MID_FRONT_LEFT,
    TANK_MID_FRONT_RIGHT,
    TANK_MID_REAR_CENTER,
    TANK_MID_REAR_LEFT,
    TANK_MID_REAR_RIGHT,
    TANK_TOP_FRONT,
    TANK_TOP_REAR_CENTER,
    TANK_TOP_REAR_LEFT,
    TANK_TOP_REAR_RIGHT
}
