package com.aranaira.magichem.foundation.enums;

public enum GrandFuseryRouterType {
    NONE,
    DAIS,
    BACK,
    PLUG_FRONT_LEFT,
    PLUG_FRONT_RIGHT,
    PLUG_MID_LEFT,
    PLUG_MID_RIGHT,
    PLUG_BACK_LEFT,
    PLUG_BACK_RIGHT,
    ASSEMBLY_MID_MID,
    ASSEMBLY_MID_LEFT,
    ASSEMBLY_MID_RIGHT,
    ASSEMBLY_MID_BACK_MID,
    ASSEMBLY_MID_BACK_LEFT,
    ASSEMBLY_MID_BACK_RIGHT,
    ASSEMBLY_UPPER_MID,
    ASSEMBLY_UPPER_LEFT,
    ASSEMBLY_UPPER_RIGHT,
    ASSEMBLY_UPPER_BACK_MID,
    ASSEMBLY_UPPER_BACK_LEFT,
    ASSEMBLY_UPPER_BACK_RIGHT,
    ASSEMBLY_SOLAR_SPHERE
}
